### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by isovector** [isovector/haskell-language-server#24]
- [x] get commit up and running
- [x] low hanging AST stuff --- at the very least to fix the big hack i put into intros
- [ ] polymorphic instantiation
- [ ] parser + custom tactics
- [ ] import things into hypothesis
- [ ] fix the explosion on destructing
- [ ] auto gas
- [ ] make auto free for split and destruct with only one datacon

**Comment by isovector** [comment]
Turned this into actual issues
